### ISSUE TITLE
Missing words on English localization 🇬🇧

### ISSUE THREAD

**Issue by hihaiu** [mudita/MuditaOS#2147]
Hello,

I was doing Finnish localization and there was some texts that didn't apparently have key value pair in English localization.

Some of these are probably developer features and there is no need for translation in my opinion, but it would be nice if the developer features were tagged with [DEV] or something.

Here is what I collected:

**Settings->Advanced**
* Information (DEV?)
* UI TEST (DEV?)
* SIM SELECT (DEV?)
* Fota update (DEV?)
* Color test (DEV?, all the sub texts were translated though)

**Settings->Display and keypad->Display light**
* Light intensity (DEV?)
* Manual brightness (DEV?)

**Settings->Network**
* Network (in menu title)

**Settings->Phone modes**
* PhoneModes (in menu title)

**Settings->Phone modes->Offline->Connection Frequency**
* ConnectionFrequency (in menu title)

**Settings->System**
* System (in menu title)

**Contacts**
* Favourites

**Contacts->ContactCard**
* FAVOURITES
* SPEED DIAL

Also maybe some of the templates could be translatable ( messages etc.)?

**Comment by GravisZro** [comment]
I dug into this issue and found that a few translation issues have since been fixed but the remaining untranslated strings are under `DEVELOPER_SETTINGS_OPTIONS` sections.  If these are not intended to ever be translated then you can safely close this ticket without further action.  However, if you wish to include these as translatable then I have made a branch for that and can create a PR.

**Comment by mjan-dev** [comment]
@hihaiu Thanks for reporting. As @GravisZro already mentioned, all the missing English translations from user interfaces have already been fixed. Only translations that may be missing are those hidden behind DEVELOPER_SETTINGS_OPTIONS flag. Those are used only for extra features accessible for development purposes. Closing issue.
