### ISSUE TITLE
Long SMS truncated, only first part is received

### ISSUE THREAD

**Issue by tobald** [mudita/MuditaOS#4202]
# 🐛 Bug report

## 📝 Description

When message contains more than 160 characters, I only receive the first part of it. I never see the rest of the batch.

(this could be linkend to #3854)

**Comment by Lefucjusz** [comment]
Hi @tobald, thanks for reporting the issue. This seems to be caused by the design of our UI - the message is not truncated, the further part is just hidden when the message is long. You need to select the message and press arrow down button to "scroll" through the message. This can be confusing and will be probably changed in one of the further releases - we'll inform you when there's some update on that matter. Implementing this change has already been reported under the https://appnroll.atlassian.net/browse/MOS-446 ticket.

**Comment by tobald** [comment]
thank you!
